eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
   
   
microservice:
  paymentservice:
      endpoints:
         endpoint:
             uri: http://ONLINESHOP-PAYMENT-SERVICE/payment/dopayment
  orderservice:
      endpoints:
         endpoint:
             uri: http://ONLINESHOP-ORDER-SERVICE/order/bookorder
